[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_escrow_program = "9r3zjQaHTyx9YeApFMP9xZyUr97ivSeG7tzt2SDpw4Qt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/matteo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
